scriptencoding utf-8
set listchars=tab:»»
if has("patch-7.4.710") | set listchars+=space:· | else | set listchars+=trail:· | endif
set listchars+=eol:¶
"vim --version | grep "\+multi_byte"
set listchars+=nbsp:☠
set title
set nohls autoindent
set noexpandtab tabstop=4 shiftwidth=4
syntax on
" set nocompatible # See https://askubuntu.com/a/353944/426176
" set mouse=v " For Alpine Linux

" If ssh through a PowerShell session then change the colorscheme
"if &term =~ "xterm-256" | colorscheme blue | endif
if $IsWindows == "True" | colorscheme blue | endif
if $OSTYPE =~ "linux" | colorscheme default | endif
"if exists('colors_name') | echo colors_name | endif

" Shortcut to rapidly toggle `set list` with CTRL+L
nmap <c-l> :set list!<CR>
nmap <c-t> :sort u<CR>
" Show line numbers
nmap <c-n> :set nu! \| :set ruler<CR>
" Reload current file
nmap <F5> :e<CR>
" Switch between vim split windows
map <F6> <C-W>w
nmap <F8> :TagbarToggle<CR>
"nnoremap / /\v # enable Extended Regular Expression search
"vnoremap / /\v

command -nargs=0 -range SortLine <line1>,<line2>call setline('.',join(sort(split(getline('.'),' ')),' '))
command -nargs=0 -range=% ReIndentXML call ReIndent_XML_with_xmlstarlet()
nnoremap yaf ?function<CR>$V%y<CR>

function SortMyAliases()
	:1
	:/^alias /,$-3sort u
endfunction
function SortBashFunctionsByName()
	:g/^function /,/^}$/-1 s/\n/<linefeed>/
	:sort /^function /
	:%s/<linefeed>/\r/g
endfunction
function ReIndent_HTML_with_xmllint()
	:%!xmllint --html --format - 2>/dev/null
endfunction
function ReIndent_XML_with_xmllint()
	:%!xmllint --xml --format - 2>/dev/null
endfunction
function ReIndent_XML_with_xmlstarlet()
	:%!xmlstarlet format - 2>/dev/null
endfunction
function ReIndent_HTML_with_pup()
	:%!pup
endfunction
function ReIndent_JSON_with_jq()
	:%!jq .
endfunction

autocmd BufNewFile,BufRead *.har set filetype=json
autocmd BufNewFile,BufRead *.dockerfile,Dockerfile* set filetype=dockerfile
autocmd BufNewFile,BufRead *.ovpn set filetype=openvpn
autocmd BufNewFile,BufRead *.octave set filetype=matlab
autocmd BufNewFile,BufRead *.tikz set filetype=tex

"autocmd StdinReadPost * set buftype=nofile
autocmd BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif "Remember last cursor position
autocmd FileType xml let &l:equalprg='xmllint --format --recover - 2>/dev/null' "Pretty print XML when '=G' is pressed
"autocmd FileType html let &l:equalprg='xmllint --html --format --recover - 2>/dev/null' "Pretty print HTML when '=G' is pressed
autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab
autocmd FileType html let &l:equalprg='pup 2>/dev/null' "Pretty print HTML when '=G' is pressed
autocmd FileType json let &l:equalprg='jq . 2>/dev/null' "Pretty print JSON when '=G' is pressed
"autocmd FileType xml exe ':silent %!xmllint --format --recover - 2>/dev/null' "Automatic indent when the file is opened
"autocmd VimEnter * nested :call tagbar#autoopen(1) "open it only if you're opening Vim with a supported file/files

"let g:tagbar_ctags_bin = "$HOME/gnu/bin/ctags"

" Initialize plugin system
call plug#begin('~/.vim/plugged')
let g:plug_window = 'enew' "Open vim-plug without a split
Plug 'vim-scripts/AdvancedSorters'
Plug 'vim-scripts/ingo-library'
Plug 'vim-scripts/matchit.zip' "use % to travel Shell's if, else, elif, fi.
Plug 'vim-scripts/python_match.vim' " use % to travel Python's if, elif, etc.
Plug 'vim-scripts/tagbar'
Plug 'vim-scripts/openvpn'
Plug 'sbdchd/vim-shebang'
Plug 'sirjofri/vim-biblereader'
Plug 'goerz/ipynb_notedown.vim'
Plug 'ivanov/vim-ipython'
call plug#end()

set ruler
set modeline
set tags+=./tags;
set incsearch "Search in 'real-time'

autocmd Filetype !vim %s/\%xa0//g
"autocmd BufRead,BufNewFile * if &filetype != 'vim' | %s/\%xa0//g | endif
autocmd BufRead,BufNewFile *.md setlocal spell "Activates spell checking for MarkDown files
