# vim: set ft=conf noet:
[english]
alang=en,eng,qaa,fr,fra
slang=en,en-orig,en-en,en-it,en-en-nP7-2PuUl7o,fr,fr-en,fr-it,fr-en-nP7-2PuUl7o,es,es-en,es-it,es-en-nP7-2PuUl7o,de,de-en,de-it,de-en-nP7-2PuUl7o,iw,iw-en,iw-it,iw-en-nP7-2PuUl7o # i.e https://github.com/mpv-player/mpv/issues/10245
ytdl-raw-options-append='sub-lang="en,en-orig,eng,enUS,en-US,en-en,en-orig,en-it,en-en-nP7-2PuUl7o,fr,fr-en,fr-it,fr-en-nP7-2PuUl7o,iw"' # i.e https://github.com/mpv-player/mpv/issues/6788

[french]
alang=fra,fr,en
slang=en,en-orig,en-en,en-it,en-en-nP7-2PuUl7o,fr,fr-en,fr-it,fr-en-nP7-2PuUl7o,es,es-en,es-it,es-en-nP7-2PuUl7o,de,de-en,de-it,de-en-nP7-2PuUl7o,iw,iw-en,iw-it,iw-en-nP7-2PuUl7o
ytdl-raw-options-append='sub-lang="fr,en,en-orig,eng,enUS,en-US"' # i.e https://github.com/mpv-player/mpv/issues/6788
