# vim: set ft=conf noet:
[best]
ytdl-format=bestvideo[vcodec^=avc1]+bestaudio/best

[fhd]
ytdl-format=fhd/full/bestvideo[vcodec^=avc1][height<=?1080][height>720]+bestaudio/bestvideo[height<=?1080]/bestvideo[ext=mp4]+bestaudio/best

[hd]
ytdl-format=22/high/bestvideo[vcodec^=avc1][height<=?720][height>540]+bestaudio/bestvideo[height<=?720]/bestvideo[ext=mp4]+bestaudio/best

[hq]
ytdl-format=hq/fsd/std/bestvideo[vcodec^=avc1][height<=?540][height>480]+bestaudio/bestvideo[height<=?540]/bestvideo[ext=mp4]+bestaudio/best

[fsd]
ytdl-format=fsd/std/bestvideo[vcodec^=avc1][height<=?480][height>360]+bestaudio/bestvideo[height<=?480]/bestvideo[ext=mp4]+bestaudio/best

[sd]
ytdl-format=18/std/bestvideo[vcodec^=avc1][height<=?360][height>240]+bestaudio/bestvideo[height<=?360]/bestvideo[ext=mp4]+bestaudio/best

[ld]
ytdl-format=ld/bestvideo[vcodec^=avc1][height<=?240][height>144]+bestaudio/bestvideo[height<=?240]/bestvideo[ext=mp4]+bestaudio/best

[vld]
ytdl-format=vld/bestvideo[vcodec^=avc1][height<=?144]+bestaudio/bestvideo[height<=?144]/bestvideo[ext=mp4]+bestaudio/best

