#!/usr/bin/env bash

installPackagesFromRepo.sh ppa:mozillateam/ppa thunderbird thunderbird-gnome-support thunderbird-locale-en-gb thunderbird-locale-en-us thunderbird-locale-en thunderbird-locale-fr
