"env","Get-Variable","","ReadOnly, AllScope"
"np","notepad","","ReadOnly, AllScope"
"unzip","expand-archive","","ReadOnly, AllScope"
#"grep","findstr","","ReadOnly, AllScope"
"grep","select-string","","ReadOnly, AllScope"
"man","get-help","","ReadOnly, AllScope"
